name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy-to-github-pages:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.6.0
      with:
        dotnet-version: 3.1
    - name: Install dependencies
      run: dotnet restore
    - name: Publish
      run: dotnet publish RandomGenerators.Client/RandomGenerators.Client.csproj -c Release -o release --nologo
    - name: GitHub Pages action
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.PUBLISH_TOKEN }}
        publish_branch: gh-pages
        publish_dir: release/wwwroot
        allow_empty_commit: false
        keep_files: false
        force_orphan: true
