# This CI build & deploy config is based on the tutorial found @ https://swimburger.net/blog/dotnet/how-to-deploy-aspnet-blazor-webassembly-to-github-pages

name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy-to-github-pages:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1
    - name: Install dependencies
      run: dotnet restore        # Run tests
    - name: Run unittests 
      run: dotnet test
    - name: Publish
      run: dotnet publish RandomGenerators.Client/RandomGenerators.Client.csproj -c Release -o release --nologo
    # changes the base-tag in index.html from '/' to 'BlazorGitHubPagesDemo' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to RandomGeneratorsWebApp
      run: sed -i 's/<base href="\/" \/>/<base href="\/RandomGeneratorsWebApp\/" \/>/g' release/wwwroot/index.html
    # copy index.html to 404.html to serve the same file when a file is not found
    - name: copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html
    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
    - name: Commit wwwroot to GitHub Pages
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.PUBLISH_TOKEN }}
        publish_branch: gh-pages
        publish_dir: release/wwwroot
        allow_empty_commit: false
        keep_files: false
        force_orphan: true
